# Generated by Django 4.2 on 2024-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20, null=True),
        ),
    ]
